## Setup

### Loading
We first import `nbtschematic` to be able to load `.schematic` files. It uses `nbtlib` to parse the nbt file and some classes inherented from `numpy` classes to store the data. 

In [1]:
from nbtschematic import SchematicFile
sf = SchematicFile.load("schematics/apple.schematic")
sf

<SchematicFile 'Schematic': Schematic({'Blocks': ByteArray([Byte(0), Byte(-97), Byte(0), Byte(-97), Byte(-97), Byte(-97), Byte(0), Byte(-97), Byte(0), Byte(-97), Byte(-97), Byte(-97), Byte(-97), Byte(-97), Byte(-97), Byte(-97), Byte(-97), Byte(-97), Byte(0), Byte(-97), Byte(0), Byte(-97), Byte(-97), Byte(-97), Byte(0), Byte(-97), Byte(0), Byte(0), Byte(0), Byte(0), Byte(0), Byte(35), Byte(0), Byte(0), Byte(0), Byte(0)]), 'Materials': String('Alpha'), 'Data': ByteArray([Byte(0), Byte(14), Byte(0), Byte(14), Byte(14), Byte(14), Byte(0), Byte(14), Byte(0), Byte(14), Byte(14), Byte(14), Byte(14), Byte(14), Byte(14), Byte(14), Byte(14), Byte(14), Byte(0), Byte(14), Byte(0), Byte(14), Byte(14), Byte(14), Byte(0), Byte(14), Byte(0), Byte(0), Byte(0), Byte(0), Byte(0), Byte(13), Byte(0), Byte(0), Byte(0), Byte(0)]), 'TileEntities': List[BlockEntity]([]), 'Entities': List[Entity]([]), 'Length': Short(3), 'WEOffsetX': Int(0), 'WEOffsetY': Int(-2), 'WEOriginZ': Int(26), 'WEOffsetZ': Int(-2), 'Hei

### Parsing
What matters to us is the `blocks` property of the `SchematicFile` object. It is a 3D array of `Block` objects. Each `Block` object is a Byte type holding the block id. To be able to use it in our model, we need to convert it into a numpy `np.array`.

In [2]:
import numpy as np

np.asarray(sf.blocks)

array([[[  0, -97,   0],
        [-97, -97, -97],
        [  0, -97,   0]],

       [[-97, -97, -97],
        [-97, -97, -97],
        [-97, -97, -97]],

       [[  0, -97,   0],
        [-97, -97, -97],
        [  0, -97,   0]],

       [[  0,   0,   0],
        [  0,  35,   0],
        [  0,   0,   0]]], dtype=int8)

## First model - cube with 9^3 blocks and 16 block types

The first model is a simple cube with 9^3 blocks and 16 block types. 

**Objective:** Get the model to classify the blocks correctly, we will only provide schematics of cubes with ONLY 1 block type, but in random positions (We will basically fill the cube with 1 block type, and then remove some blocks randomly).

**Why:** This is to make sure we are able to train the model to classify the blocks correctly, then we will move on to more complex models where it will actually be classifying multiple block structures.

### Valid blocks

We will only be using the following blocks:
**Air, Dirt, Oak Log, Oak Leaves, Stone Brick, Cobblestone, Glass, Sandstone, Redstone Lamp, Iron Bars, Stone Brick, Bricks, Block of Quartz, White Wool, Bookshelf, White Terracotta, Nether Brick**


I already have a schematic file with all these blocks lined up in a row, so we will just load that and use it to get the block ids.

In [3]:
import pandas as pd

all_blocks_schematic = SchematicFile.load("schematics/allblocks.schematic")

# We reverse the array because I want the air block to be in the front, it doesn't really matter though
blocks = np.asarray(all_blocks_schematic.blocks).flatten()[::-1]

# Labels are in the same order as the blocks
labels = np.array(['Air', 'Dirt', 'Oak Log', 'Oak Leaves', 'Stone Brick', 'Cobblestone', 'Glass', 'Sandstone', 'Redstone Lamp', 'Iron Bars', 'Bricks', 'Block of Quartz', 'White Wool', 'Bookshelf', 'White Terracotta', 'Nether Brick'])

# Create a table with the labels (block names), block ids and index in the array
table = np.array([labels, blocks, np.arange(len(labels))]).T

# print the table using pandas
pd.DataFrame(table, columns=['Label', 'Block ID', 'Index']).style.hide()

### One Hot Encoding the blocks

We will use a one hot encoding to represent the blocks. We will have a 16 length vector, with each index representing a block type. The index of the block type will be set to 1, and the rest will be 0.

**Why:** Block types is a categorical variable, and we need to represent it in a way that the model can understand. One hot encoding is a good way to do this. If we were to use a simple integer encoding, the model would think that the block types are ordinal, and that the block type with the highest integer is the best block type. This is not the case, so we use one hot encoding.

### Converting the blocks to one hot encoding

We will use the `block_ids` array to convert the blocks to one hot encoding. We will define a function `one_hot` to create a one hot encoded array and a `convert_blocks_to_one_hot` that takes an id an a dictionnary mapping the block ids to the one hot encoding index.

In [4]:
def one_hot(lenght: int, index: int)->np.array:
    """
    Creates a one hot array of the given lenght and sets the index to 1
    """
    one_hot = np.zeros((lenght))
    one_hot[index] = 1
    return one_hot

def convert_blocks_to_one_hot(block_id: int, possible_blocks: dict)->np.array:
    """
    Converts an array of block ids to a one hot array
    """
    return one_hot(len(possible_blocks), possible_blocks.get(block_id) or 0)

# We need to convert the block ids array to a dictionary of block ids and their index in the array
blocks_dict:dict = {block_id: index for index, block_id in enumerate(blocks)}

# convert_blocks_to_one_hot(3, blocks_dict)
one_hot(16, 0)

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Creating the dataset

For other models, the dataset will be created inside Minecraft and exported as a `.schematic` file. For this model, we will create the dataset in python. We will randomly set blocks in the cube to a block type with the `random` module. Remember, in this model, **we are only training the model to classify the blocks correctly**, so we will only use 1 block type per cube. This should be a simple task.

In [5]:
from random import random
from typing import List
import torch

dataset = []

class RandomCube:
    def __init__(self, block_index: int, dimensions: int=3, air_frequency=0.25):
        self.block_index = block_index
        self.dimensions = dimensions
        self.air_frequency = air_frequency
        self.data:np.array = []
        self.target:np.array = []

        self.create()

    def create(self):
        for x in range(self.dimensions):
            self.data.append([])
            for y in range(self.dimensions):
                self.data[x].append([])
                for z in range(self.dimensions):
                    if random() > self.air_frequency:
                        self.data[x][y].append(one_hot(16, self.block_index))
                    else:
                        self.data[x][y].append(one_hot(16, 0))

        self.data = np.array(self.data)
        self.target = one_hot(16, self.block_index)

        return self
    
    @property
    def count(self: int)->int:
        # Count each block and return a dict
        block_count = {}

        for x in self.data:
            for y in x:
               for z in y:
                   for i, is_there in enumerate(z):
                        if is_there == 1:
                            block_count[i] = block_count.get(i, 0) + 1

        return block_count
                           
    def __repr__(self):
        return f"RandomCube{{count={self.count}, data={self.data}, target={self.target}}}"
    
    def __str__(self):
        return f"RandomCube{{count={self.count}, data={self.data}, target={self.target}}}"
    
    def to_torch(self):
        self.data = torch.tensor(self.data, dtype=torch.float32)
        self.target = torch.tensor(self.target, dtype=torch.float32)

        return self

RandomCube(block_index=1)

RandomCube{count={1: 14, 0: 13}, data=[[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


 [[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

Now that we have this RandomCube class, we can create a dataset about 70000 cubes. We will use 50000 for training, 20000 for testing.

In [6]:
from random import randint

def generate_dataset(size: int=1000, dimensions: int=3, air_frequency: float=0.25)->List[RandomCube]:
    dataset = []

    for _ in range(size):
        dataset.append(RandomCube(block_index=randint(0, 15), dimensions=dimensions, air_frequency=air_frequency))

    return dataset

dataset = generate_dataset(size=70000, dimensions=3, air_frequency=0.25)
print(f"Generated {len(dataset)} cubes, each cube has a size of {dataset[0].data.shape} and a target of {dataset[0].target.shape}")

Generated 70000 cubes, each cube has a size of (3, 3, 3, 16) and a target of (16,)


### Creating the model

It is a 4D model as we have 4 dimensions: x, y, z, and block type. For this simple model, we will use a simple NN with 2 hidden layers. We will use the `relu` activation function for the hidden layers, and `softmax` for the output layer. We will use the `categorical_crossentropy` loss function, and the `adam` optimizer.

In [7]:
import torch
import torch.nn as nn

class BlockClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(432, 64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Linear(64, 16),
        )

    def forward(self, x):
        x = self.flatten(x)
        x = x.flatten()
        logits = self.linear_relu_stack(x)
        return logits
    

### Predicting the blocks

Let's create a random tensor and pass it through the model to see what it predicts. It will give a random result as the model is not trained yet. The weights are initialized randomly.

In [8]:
model_1 = BlockClassifier().to("cuda")
random_prediction = torch.rand(3,3,3,16)
prediction = model_1(random_prediction.cuda())

prediction = torch.sort(prediction, descending=True)

for index, value in enumerate(prediction.indices):
    print(f"{index+1}. {labels[value]} ~ {prediction.values[index] * 100:.2f}%")

1. Bricks ~ 10.92%
2. Sandstone ~ 8.36%
3. Glass ~ 4.76%
4. Dirt ~ 3.82%
5. Air ~ -0.18%
6. Oak Log ~ -0.19%
7. Redstone Lamp ~ -0.22%
8. Bookshelf ~ -0.46%
9. Oak Leaves ~ -0.61%
10. Nether Brick ~ -0.99%
11. White Terracotta ~ -1.58%
12. Block of Quartz ~ -5.57%
13. Cobblestone ~ -6.20%
14. White Wool ~ -6.43%
15. Iron Bars ~ -16.22%
16. Stone Brick ~ -23.87%


### Training the model

We will train the model for 10 epochs, with a batch size of 32. We will use the `ModelCheckpoint` callback to save the model after each epoch. We will also use the `EarlyStopping` callback to stop the training if the validation loss does not improve for 3 epochs.

In [12]:
def train(dataset, model, loss_fn, optimizer, num_epochs=10):
    size = len(dataset)

    for epoch in range(num_epochs):
        print(f"Epoch {epoch+1}\n-------------------------------")
        for batch, cube in enumerate(dataset):
            # Transform cube data and target to tensors
            cube.to_torch()
            
            # Compute prediction and loss
            pred = model(cube.data.cuda())
            loss = loss_fn(pred, cube.target.cuda())

            # Backpropagation
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            if batch % 5000 == 0:
                loss, _ = loss.item(), batch * len(cube.data)
                print(f"epoch {epoch+1} batch {batch} loss {loss:>7f} [{batch:>5d}/{size:>5d}]")
    

training_dataset = dataset[:50000]
testing_dataset = dataset[50000:]

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model_1.parameters(), lr=1e-3)

train(training_dataset, model_1, loss_fn, optimizer, num_epochs=3)

Epoch 1
-------------------------------
epoch 1 batch 0 loss 0.000803 [    0/50000]


/tmp/ipykernel_94891/3712570090.py:54: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.data = torch.tensor(self.data, dtype=torch.float32)
/tmp/ipykernel_94891/3712570090.py:55: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.target = torch.tensor(self.target, dtype=torch.float32)


epoch 1 batch 5000 loss 0.000450 [ 5000/50000]
epoch 1 batch 10000 loss 0.001362 [10000/50000]
epoch 1 batch 15000 loss 0.000693 [15000/50000]
epoch 1 batch 20000 loss 0.000530 [20000/50000]
epoch 1 batch 25000 loss 0.000216 [25000/50000]
epoch 1 batch 30000 loss 0.000213 [30000/50000]
epoch 1 batch 35000 loss 0.000456 [35000/50000]
epoch 1 batch 40000 loss 0.000983 [40000/50000]
epoch 1 batch 45000 loss 0.000343 [45000/50000]
Epoch 2
-------------------------------
epoch 2 batch 0 loss 0.000525 [    0/50000]
epoch 2 batch 5000 loss 0.000310 [ 5000/50000]
epoch 2 batch 10000 loss 0.000939 [10000/50000]


In [10]:
def test(dataset, model, loss_fn):
    size = len(dataset)
    num_batches = len(dataset)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for batch, cube in enumerate(dataset):
            cube.to_torch()

            pred = model(cube.data.cuda())
            test_loss += loss_fn(pred, cube.target.cuda()).item()

            correct += (pred.argmax(0) == cube.target.argmax(0)).item()

            if batch % 2000 == 0:
                loss, current = test_loss / (batch + 1), batch * len(cube.data)
                print(f"testing : [{current:>5d}/{size:>5d}]")

    test_loss /= num_batches
    correct /= size

    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

test(testing_dataset, model_1, loss_fn)

testing : [    0/20000]
testing : [ 6000/20000]
testing : [12000/20000]
testing : [18000/20000]
testing : [24000/20000]
testing : [30000/20000]
testing : [36000/20000]
testing : [42000/20000]
testing : [48000/20000]
testing : [54000/20000]
Test Error: 
 Accuracy: 100.0%, Avg loss: 0.001363 



### Playing around with air cubes

Most cubes have some air blocks, so let's see how the model performs on cubes with way more air blocks than other blocks. 

In [11]:
RandomCube(block_index=1, air_frequency=0.75).count

{0: 20, 1: 7}

### Results

The model gave us a 100% accuracy on the testing set. This is expected as the model is very simple and the task is very simple. We will now move on to more complex models.


